M7R0
I&mylib=6"%&falseGE\[l@%&deltyGf*6*%$a1sG%$b1sG%$c1sG%$d1sG%$a2sG%$b2sG%$c2sG%$
d2sG6)%$dabG%$dacG%$dadG%$dbcG%$dbdG%$dcdG%$RezGF$F$C3>8$-%'factorG6#,&*&9$"""9
)FCFC*&9(FC9%FC!"">8%-F>6#,&*&FBFC9*FCFC*&FFFC9&FCFH>8&-F>6#,&*&FBFC9+FCFC*&FFF
C9'FCFH>8'-F>6#,&*&FGFCFOFCFC*&FDFCFQFCFH>8(-F>6#,&*&FGFCFXFCFC*&FDFCFZFCFH>8)-
F>6#,&*&FQFCFXFCFC*&FOFCFZFCFH>8*-F>6#,.*$FS""$FC*(F<FCFSFCFdoFC!"#*&FJ""#FdoFC
FC*&F<FCF]oFdpFC*(F<FCFfnFCFdoFCFH*(FJFCFSFCF]oFCFH-%&printG6#%2ishodnaya_siste
maG-Fip6&FBFGFQFZ-Fip6&FFFDFOFX-Fip6$%)delta_abGF<-Fip6$%)delta_acGFJ-Fip6$%)de
lta_adGFS-Fip6$%)delta_bcGFfn-Fip6$%)delta_bdGF]o-Fip6$%)delta_cdGFdo-Fip6,%#R3
GQ"~F$F[p%+sostoit_izGF_pFcpFep,$FapFbp,$FfpFH,$FgpFH6#Q9schitaet~delty~v~siste
meF$F$F$%%l1pdGf*6,%$p1nG%$q1nG%$t1nG%$p2nG%$q2nG%$t2nG%$r1nG%$s1nG%$r2nG%$s2nG
6,%%p1nnG%%q1nnG%%t1nnG%%p2nnG%%q2nnG%%t2nnG%'rezultG%%rez2G%$D1nG%$D2nGF$F$C7>
F<-F>6#*&,.*(FOFdp9-FCFBFCFC*(FOFdpFXFCFZFCFH**9,FCFGFCFOFCF[uFCFC**FOFCFFFCFXF
CF^uFCFH*(F^uFdpF[uFCFQFCFC*(F^uFdpFXFCFDFCFHFC,&*&FOFCF[uFCFC*&F^uFCFXFCFHFH>F
J-F>6#*&,2**FOFCFXFCF[uFCFBFCFdp*(FXFdpFOFCFZFCFbp*(F[uFdpFGFCFOFCFC**FXFCF[uFC
F^uFCFGFCFC**FXFCF[uFCFOFCFFFCFH*(FXFdpFFFCF^uFCFH*(F[uFdpF^uFCFQFCFdp**F^uFCF[
uFCFXFCFDFCFbpFCFbuFH>FS-F>6#*&,.*(FXFdpF[uFCFBFCFC*&FXF`pFZFCFH*(FXFCF[uFdpFGF
CFC*(FXFdpF[uFCFFFCFH*&F[uF`pFQFCFC*(F[uFdpFXFCFDFCFHFCFbuFH>Ffn-F>6#,$*&,.*(FO
FdpF^uFCFBFCFC*&FOF`pFZFCFH*(FOFCF^uFdpFGFCFC*(FOFdpF^uFCFFFCFH*&F^uF`pFQFCFC*(
F^uFdpFOFCFDFCFHFCFbuFHFH>F]o-F>6#,$*&,2**FOFCFXFCF^uFCFBFCFdpF\uFbpF]uFC*(F^uF
dpFGFCFXFCFC*(FOFdpFFFCF[uFCFHF_uFHF`uFdp**F^uFCF[uFCFOFCFDFCFbpFCFbuFHFH>Fdo-F
>6#,$*&,.*(FXFdpF^uFCFBFCFCF[vFHF]vFCF^vFHF`vFC*(F[uFdpFOFCFDFCFHFCFbuFHFH>F[p-
F>6#,&*$,&FAFC*&FQFCFZFCFHFdpFC*&,&*&FBFCFFFCFC*&FGFCFZFCFHFC,&*&FGFCFDFCFCFPFH
FCFH>8+-F>6#,&*$,&*&F<FCFdoFCFC*&FfnFCFSFCFHFdpFC*&,&*&F<FCF]oFCFC*&FfnFCFJFCFH
FC,&*&FJFCFdoFCFC*&F]oFCFSFCFHFCFH>8,-F>6#,&*$FJFdpFC*&F<FCFSFC!"%>8--F>6#,&*$F
]oFdpFC*&FfnFCFdoFCF_[l-Fip6%%*rezultantGFerF[p-Fip6*%6isxodnye_koefficientyGFB
FGFQFerFZFFFD-Fip6(%'zamenaGFOFXFerF^uF[u-Fip6%%-delta_zamenyGFer-F>6#-%)simpli
fyG6#-%&deltaG6&FOFXF^uF[u-Fip6#%:koefficienty_posle_zamenyG-Fip6%F<FJFS-Fip6%F
fnF]oFdo-Fip6$%)discrim1GFiz-Fip6$%)discrim2GFa[l-Fip6$%#R2GFiy-Fip6#Q_r-------
-------------------------------------------------------------------------------
------------------------------F$6#Q9p,q,t~pri~zamene~pri~l=1F$F$F$%*zamprocl1Gf
*6.%%alpnG%&betanGF_sF`sFasFbsFcsFds%$r1pG%$s1pG%$r2pG%$s2pG62%%a1nnG%%b1nnG%%c
1nnG%%d1nnG%%a2nnG%%b2nnG%%c2nnG%%d2nnGF`tFjsF[tF\tF]tF^tF_tFatF$F$C6>F<-F>6#*&
FBFCFQFC>FJ-F>6#,&*&FBFCFZFCFC*&FQFCFGFCFC>FS-F>6#,&FdyFCFeyFC>Ffn-F>6#FE>F]o-F
>6#FA>Fdo-F>6#,&FNFCFgyFC>F[p-F>6#,&FWFCFjnFC>Fiy-F>6#Fao>Fa[l-F>6#*&,.*(F^uFdp
9/FCFQFCFC*(F^uFdpF[uFCFDFCFH**9.FCFZFCF^uFCFhalFCFC**F^uFCFOFCF[uFCF[blFCFH*(F
[blFdpFhalFCFFFCFC*(F[blFdpF[uFCFXFCFHFC,&*&F^uFCFhalFCFC*&F[blFCF[uFCFHFH>8.-F
>6#*&,2**F^uFCF[uFCFhalFCFQFCFdp*(F[uFdpF^uFCFDFCFbp*(FhalFdpFZFCF^uFCFC**F[uFC
FhalFCF[blFCFZFCFC**F[uFCFhalFCF^uFCFOFCFH*(F[uFdpFOFCF[blFCFH*(FhalFdpF[blFCFF
FCFdp**F[blFCFhalFCF[uFCFXFCFbpFCF_blFH>8/-F>6#*&,.*(F[uFdpFhalFCFQFCFC*&F[uF`p
FDFCFH*(F[uFCFhalFdpFZFCFC*(F[uFdpFhalFCFOFCFH*&FhalF`pFFFCFC*(FhalFdpF[uFCFXFC
FHFCF_blFH>80-F>6#,$*&,.*(F^uFdpF[blFCFQFCFC*&F^uF`pFDFCFH*(F^uFCF[blFdpFZFCFC*
(F^uFdpF[blFCFOFCFH*&F[blF`pFFFCFC*(F[blFdpF^uFCFXFCFHFCF_blFHFH>81-F>6#,$*&,2*
*F^uFCF[uFCF[blFCFQFCFdpFialFbpFjalFC*(F[blFdpFZFCF[uFCFC*(F^uFdpFOFCFhalFCFHF
\blFHF]blFdp**F[blFCFhalFCF^uFCFXFCFbpFCF_blFHFH>82-F>6#,$*&,.*(F[uFdpF[blFCFQF
CFCFiblFHF[clFCF\clFHF^clFC*(FhalFdpF^uFCFXFCFHFCF_blFHFH>83-F>6#,&*$,&*&Fa[lFC
FeelFCFC*&F]dlFCFaclFCFHFdpFC*&,&*&Fa[lFCFjdlFCFC*&F]dlFCFcblFCFHFC,&*&FcblFCFe
elFCFC*&FjdlFCFaclFCFHFCFH>Fiz-F>6#,&*$,&FhoFC*&FDFCFFFCFHFdpFC*&,&*&FQFCFOFCFC
FboFHFC,&*&FZFCFXFCFC*&FOFCFFFCFHFCFH-Fip6%%'R2_isxGFerFiz-Fip6%F\\l-F>6#FB-F>6
#FG-Fip6(-F>6#FQ-F>6#FZ-F>6#FF-F>6#FD-F>6#FO-F>6#FX-Fip6#-%(zamprocG6.F<FJFSFfn
F]oFdoF[pFiyF^uF[uF[blFhal6#Qgodelaet~lineinuu~zamenu~v~sisteme,zadannoy~obw.mn
ojitelem~1~deg~i~matricey~H3F$F$F$%(jordle0Gf*6*%$a1pG%$b1pG%$c1pG%$d1pG%$a2pG%
$b2pG%$c2pG%$d2pG6.%%P1nnG%%P2nnGF3%%chisG%%znamG%$obwG%#omG%#hpG%*f_dla_schG%#
scG%-sobst_chislaG%#mnGF$F$C*>F<-F>6#-Ff\l6#-%"PG6(FBFGFQFZ%#x1G%#x2G>FJ-F>6#-F
f\l6#-Ff[m6(FFFDFOFXFh[mFi[m>Ffn-%&numerG6#*&F<FCFJFH>F]o-%&denomGFd\m>Fdo-Ff\l
6#*&F<FCFfnFH@%/-%&coeffG6$Fdo*$Fh[mFdpFCC$>F[p-%'MatrixG6#7#7%F_]m*&-F`]m6$Fdo
Fh[mFCFi[mFH-F`]m6$Fdo*$Fi[mFdp>Fiy-Ff]m6#7$7$-F`]m6$FfnFh[m-F`]m6$FfnFi[m7$-F`
]m6$F]oFh[m-F`]m6$F]oFi[mC&>FaclF_]m>F[p-Ff]m6#7#7%*&F_]mFCFaclFH*(F[^mFCFi[mFH
FaclFH*&F]^mFCFaclFH>Fiy-Ff]m6#7$7$*&Fe^mFCFaclFC*&Fg^mFCFaclFC7$*&Fj^mFCFaclFC
*&F\_mFCFaclFC@$2&F[p6$FCFC""!C$>F[p,$F[pFH>Fiy,$FiyFH-%&l2alpG6)Fd`m&F[p6$FCFd
p&F[p6$FCF`p-%%sqrtG6#,&*$,&&FiyFe`mFC&Fiy6$FdpFdpFHFdpFH*&&Fiy6$FdpFCFC&FiyF`a
mFCF_[lFhamFf`m,$F]bmFdp-%$l2pG6*FiamF_bmF]bmFjamFcamFhamFf`mF`bm6#Q_oprivodit~
sistemu~k~jord~forme~v~sluchae~l=2,~D<0,zadannoy~matricey~AF$F$F$%+zamprocl1oGf
*Fb^lFi^lF$F$C6>F<Fd_l>FJFh_l>FSF^`l>FfnFb`l>F]oFe`l>FdoFh`l>F[pF\al>FiyF`al>Fa
[lFcal>FcblFdbl>FaclFbcl>F]dlF^dl>FjdlF[el>FeelFfel>F^flF_fl>FizF^glFjglF]hlFch
l-Fip6#-%)zamprocoGFeilFfilF$F$Fdilf*6.%#a1G%#b1G%#c1G%#d1G%#a2G%#b2G%#c2G%#d2G
%#r1G%#s1G%#r2G%#s2G6EFj^lF[_lF\_lF]_lF^_lF__lF`_lFa_l%$a1nG%$b1nG%$c1nG%$d1nG%
$a2nG%$b2nG%$c2nG%$d2nG%&DeltaG%#i1G%#i2G%#i3G%#i4G%#i5G%#i6G%#i7G%#i8G%#ixG%#m
1G%#m2G%#m3G%#m4G%#m5G%#m6G%#m7G%#m8G%#mxGF$F$CO>84-&F"6#Fi\l6&F^uF[uF[blFhal>F
iz*&,&*&FhalFC-Ff[m6(FBFGFQFZF^uF[blFCFC*&F[uFC-Ff[m6(FFFDFOFXF^uF[blFCFHFCFifm
FH>Fa[l*&,:**FBFCF^uFdpF[uFCFhalFCF`p*,FGFCF^uFCF[uFCF[blFCFhalFCFdp*(FGFCF^uFd
pFhalFdpFC**FQFCF^uFCF[blFCFhalFdpFdp**FQFCF[uFCF[blFdpFhalFCFC*(FZFCF[blFdpFha
lFdpF`p*(FFFCF^uFdpF[uFdp!"$**FDFCF^uFCF[uFdpF[blFCFbp**FDFCF^uFdpF[uFCFhalFCFH
*,FOFCF^uFCF[uFCF[blFCFhalFCFbp*(FOFCF[uFdpF[blFdpFH**FXFCF[uFCF[blFdpFhalFCFah
mFCFifmFH>Fcbl*&,:**FBFCF^uFCF[uFdpFhalFCF`p**FGFCF^uFCF[uFCFhalFdpFdp**FGFCF[u
FdpF[blFCFhalFCFC**FQFCF[uFCF[blFCFhalFdpFdp*(FQFCF^uFCFhalF`pFC*(FZFCF[blFCFha
lF`pF`p*(FFFCF^uFCF[uF`pFahm**FDFCF^uFCF[uFdpFhalFCFbp*(FDFCF[uF`pF[blFCFH**FOF
CF[uFdpF[blFCFhalFCFbp**FOFCF^uFCF[uFCFhalFdpFH**FXFCF[uFCF[blFCFhalFdpFahmFCFi
fmFH>Facl*&,&*&FhalFC-Ff[m6(FBFGFQFZF[uFhalFCFC*&F[uFC-Ff[m6(FFFDFOFXF[uFhalFCF
HFCFifmFH>F]dl*&,&*&F[blFCFbgmFCFH*&F^uFCFegmFCFCFCFifmFH>Fjdl*&,:*(FFFCF^uF`pF
[uFCF`p**FDFCF^uFdpF[uFCF[blFCFdp*(FDFCF^uF`pFhalFCFC**FOFCF^uFdpF[blFCFhalFCFd
p**FOFCF^uFCF[uFCF[blFdpFC**FXFCF^uFCF[blFdpFhalFCF`p**FBFCF^uFdpF[uFCF[blFCFah
m**FGFCF^uFCF[uFCF[blFdpFbp**FGFCF^uFdpF[blFCFhalFCFH**FQFCF^uFCF[blFdpFhalFCFb
p*(FQFCF[uFCF[blF`pFH*(FZFCF[blF`pFhalFCFahmFCFifmFH>Feel*&,:F`hmF`pFchmFdpFbhm
FCFdhmFdp*(FOFCF^uFdpFhalFdpFC**FXFCF^uFCF[blFCFhalFdpF`p**FBFCF^uFCF[uFdpF[blF
CFahmF[hmFbp*(FGFCF[uFdpF[blFdpFHF^hmFbpF]hmFHF_hmFahmFCFifmFH>F^fl*&,&*&F[blFC
FjimFCFH*&F^uFCF]jmFCFCFCFifmFH>F<-Ff\l6#-F>6#-Ff\l6#-%'normalG6#-Ff\l6#Fiz>FJ-
Ff\l6#-F>6#-Ff\l6#-Fg\n6#-Ff\l6#Fa[l>FS-Ff\l6#-F>6#-Ff\l6#-Fg\n6#-Ff\l6#Fcbl>Ff
n-Ff\l6#-F>6#-Ff\l6#-Fg\n6#-Ff\l6#Facl>F]o-Ff\l6#-F>6#-Ff\l6#-Fg\n6#-Ff\l6#F]dl
>Fdo-Ff\l6#-F>6#-Ff\l6#-Fg\n6#-Ff\l6#Fjdl>F[p-Ff\l6#-F>6#-Ff\l6#-Fg\n6#-Ff\l6#F
eel>Fiy-Ff\l6#-F>6#-Ff\l6#-Fg\n6#-Ff\l6#F^fl>Fiz-Ff\l6#-F>6#-Ff\l6#-Fg\n6#-Ff\l
F`hl>Fa[l-Ff\l6#-F>6#-Ff\l6#-Fg\n6#-Ff\lFbhl>Fcbl-Ff\l6#-F>6#-Ff\l6#-Fg\n6#-Ff
\lFfhl>Facl-Ff\l6#-F>6#-Ff\l6#-Fg\n6#-Ff\lFhhl>F]dl-Ff\l6#-F>6#-Ff\l6#-Fg\n6#-F
f\lFjhl>Fjdl-Ff\l6#-F>6#-Ff\l6#-Fg\n6#-Ff\lF\il>Feel-Ff\l6#-F>6#-Ff\l6#-Fg\n6#-
Ff\lF^il>F^fl-Ff\l6#-F>6#-Ff\l6#-Fg\n6#-Ff\lF`il@%/F<Ff`mC$>85Ff`m>8>Ff`mC$>F\g
nFC>F^gnFC@%/FJFf`mC$>86Ff`m>8?Ff`mC$>FfgnFdp>FhgnFC@%/FSFf`mC$>87Ff`m>8@Ff`mC$
>F`hnF`p>FbhnFC@%/FfnFf`mC$>88Ff`m>8AFf`mC$>Fjhn""%>F\inFC@%/F]oFf`mC$>89Ff`m>8
BFf`mC$>FeinF_in>FginFC@%/FdoFf`mC$>8:Ff`m>8CFf`mC$>F_jnF`p>FajnFC@%/F[pFf`mC$>
8;Ff`m>8DFf`mC$>FijnFdp>F[[oFC@%/FiyFf`mC$>8<Ff`m>8EFf`mC$>Fc[oFC>Fe[oFC>8=,2F
\gnFCFfgnFCF`hnFCFjhnFCFeinFCF_jnFCFijnFCFc[oFC>8F,2F^gnFCFhgnFCFbhnFCF\inFCFgi
nFCFajnFCF[[oFCFe[oFCFhp-Fip6&FizFa[lFcblFacl-Fip6&F]dlFjdlFeelF^fl-Fip6(F_\l-F
f\l6#-F>6#-Ff\l6#F^u-Ff\l6#-F>6#-Ff\l6#F[uFer-Ff\l6#-F>6#-Ff\l6#F[bl-Ff\l6#-F>6
#-Ff\l6#Fhal-Fip6%Fb\lFer-Ff\l6#-F>6#-Ff\l6#-Fi\lF]gm-Fip6)%&nenulGFerF]\oFer%&
indexGFerFj[o-Fip6#%5sistema_posle_zamenyG-Fip6&F<FJFSFfn-Fip6&F]oFdoF[pFiy-Fip
6#Q]r--------------------------------------------------------------------------
----------------------------------------F$6#QAdelaet~lineinuu~zamenu~v~sistemeF
$F$F$%.jord_ravno_02Gf*6)Fc^lFd^l%'gammanGF_sF`sFbsFcs66FdjlFejlF3FfjlFgjlFhjlF
ijlFjjlF[[mF\[mF][mF^[mF[jlF\jlF]jlF^jlF_jlF`jlFajlFbjlF$F$C2>F]dl-F>6#-Ff\l6#F
[`l>Fjdl-F>6#-Ff\lF_`l>Feel-F>6#-Ff\l6#,&FEFCFayFC>F^fl-F>6#-Ff\l6#FP>Fifm-F>6#
-Ff\lFf`l>F\gn-F>6#-Ff\lFi`l>Ffgn-F>6#-Ff\l6#,&FjnFCF[oFC>F`hn-F>6#-Ff\l6#Ffgl>
F<-F>6#-Ff\l6#-Ff[m6(F]dlFjdlFeelF^flFh[mFi[m>FJ-F>6#-Ff\l6#-Ff[m6(FifmF\gnFfgn
F`hnFh[mFi[m>FfnFb\m>F]oFg\m>FdoFj\m@%F^]mC$>F[pFe]m>FiyFa^mC&>FaclF_]m>F[pFa_m
>FiyFi_m@$Fc`mC$>F[pFi`m>FiyF[am-F]am6)Fd`mF_amFaamFf`m,$F_bmFdpFdp,&FjamFCFiam
FH-Fbbm6*FiamF_bmF]bmFjamFf`mFbdoFdpFcdo6#Qioprivodit~sistemu~k~jord~forme~v~sl
uchae~l=2,~Dp<0,Dh=0,~zadannoy~alp,bet,gam,HF$F$F$%(compzamGf*6*%$r11G%$s11G%$r
21G%$s21G%$r12G%$s12G%$r22G%$s22G6%%#L1G%#L2G%$L12GF$F$C4>F<-Ff]mF[bm>-F<Fe`mFB
>-F<F`amFG>-F<F^bmFQ>-F<F[bmFZ>FJFieo>-FJFe`mFF>-FJF`amFD>-FJF^bmFO>-FJF[bmFX>F
SFieo>FS-_%.LinearAlgebraG%5MatrixMatrixMultiplyG6$F<FJ-Fip6#%,perv_zamenaG-Fip
6'FBFGFerFQFZ-Fip6#%,vtor_zamenaG-Fip6'FFFDFerFOFX-Fip6#%2kompoziciya_zamenG-Fi
p6'-Fg\n6#-FSFe`m-Fg\n6#-FSF`amFer-Fg\n6#-FSF^bm-Fg\n6#-FSF[bm6#Q9delaet~kompoz
iciyu~zamenF$F$F$%$pm2Gf*Fjil67FdjlFejlF3F4F5F6F7F8F9FfjlFgjlFhjlFijlFjjl%'delt
aHGF[[mF\[mF][mF^[m%#DpG%#DHGF$F$C9>F<Fa[m>FJF[\m>Fa[lFb\m>FcblFg\m>Facl-Ff\l6#
*&F<FCFa[lFH@%0-F`]m6$FaclFb]mFf`mC%>FfgnF`jo>F]dl-Ff]m6#7#7%*&F`joFCFfgnFH*(-F
`]m6$FaclFh[mFCFi[mFHFfgnFH*&-F`]m6$FaclF_^mFCFfgnFH>Fjdl-Ff]m6#7$7$*&-F`]m6$Fa
[lFh[mFCFfgnFC*&-F`]m6$Fa[lFi[mFCFfgnFC7$*&-F`]m6$FcblFh[mFCFfgnFC*&-F`]m6$Fcbl
Fi[mFCFfgnFC@%0F[[pFf`mC%>Ffgn*&F[[pFCFi[mFH>F]dl-Ff]m6#7#7%Ff`mFjjoF][p>FjdlFa
[pC%>FfgnF^[p>F]dl-Ff]m6#7#7%Ff`mFf`mF][p>FjdlFa[p>Feel-F>6#-Ff\l6#,&*&&FjdlFe`
mFC&FjdlF[bmFCFC*&&FjdlF`amFC&FjdlF^bmFCFH>Fjhn-F>6#-Ff\l6#,&*$,&F\^pFCF]^pFCFd
pFCFeelF_[l>FSF=>FfnFK>F]oFT>FdoFgn>F[pF^o>FiyFeo>Fiz-F>6#,.*$F]oF`pFC*(FSFCF]o
FCFiyFCFbp*&FfnFdpFiyFCFC*&FSFCF[pFdpFC*(FSFCFdoFCFiyFCFH*(FfnFCF]oFCF[pFCFH>F`
hn-F>6#-Ff\l6#,&*$&F]dlF`amFdpFC*&&F]dlFe`mFC&F]dlFbamFCF_[lF\qF^q-Fip6#F<-Fip6
#FJ-Fip6$F]dlFjdl-Fip6%/%$D_0GF`hn/.%"DGFjhn/%(delta_HGFeel-Fip6%%3sobstvennye_
chislaGFer-_F_go%,EigenvaluesGFa`n6#Qcpraskladyvaet~mnogochleny~v~sisteme,zadan
noy~matricey~A,~schitaet~delty,~rez,~obw.mnoj.,HF$F$F$%&l1alpGf*6(Fc^lFd^lFesFf
sFgsFhs6%%&alpnnG%'betannG%(gammannGF$F$C'>F<-F>6#,&Ff_lFCFEFC>FJ-F>6#,&F[`lFCF
gyFC-Fip6%F\\lFBFG-Fip6(F_\lFQFZFerFFFD-Fip6%F]]lF<FJ6#Q?alpha,~beta~pri~zamene
~pri~l=1F$F$F$Ff[mf*6(%"aG%"bG%"cG%"dG%"xG%"yGF$6$%)operatorG%&arrowGF$,**&FBFC
FFF`pFC*(FGFCFFFdpFDFCFC*(FQFCFFFCFDFdpFC*&FZFCFDF`pFCF$F$F$%*zamprocl2Gf*6-Fc^
lFd^lFi_oF_sF`sFbsFcsFgdmFhdmFidmFjdm6*Fj^lF[_lF\_lF]_lF^_lF__lF`_lFa_lF$F$C+>F
<F]`o>FJFb`o>FSFf`o>FfnF\ao>F]oFaao>FdoFeao>F[pFiao>FiyF_bo-Fdil6.F<FJFSFfnF]oF
doF[pFiyFXF^uF[uF[bl6#Qgodelaet~lineinuu~zamenu~v~sisteme,zadannoy~obw.mnojitel
em~2~deg~i~matricey~H2F$F$F$%'l1systGf*6*Fc^lFd^lF_sF`sFasFbsFcsFds64F\emF]emF^
emF_emF`emFaemFbemFcemF`tFeemFfemFgemFhemFiemFjemF[fmF\fmF]fmF$F$C;>F<Ff_l>FJFj
_l>FSF``l>FfnFE>F]oFA>FdoFj`l>F[pF^al>FiyFao>FizF^gl@%Fifn>Fa[lFf`m>Fa[lFC@%Fcg
n>FcblFf`m>FcblFdp@%F]hn>FaclFf`m>FaclF`p@%Fghn>F]dlFf`m>F]dlF_in@%Fbin>FjdlFf`
m>FjdlF_in@%F\jn>FeelFf`m>FeelF`p@%Ffjn>F^flFf`m>F^flFdp@%F`[o>FifmFf`m>FifmFC>
F\gn,2Fa[lFCFcblFCFaclFCF]dlFCFjdlFCFeelFCF^flFCFifmFCF[cp-Fip6(FQFZFFFDFOFX-Fi
p6$Fi[lFiz-Fip6#%(systemaGF]_oF__o-Fip6%Fi^oFerF\gn6#Q9po~koef-tam~daet~sistemy
F$F$F$%%zam1Gf*6&FesFfsFgsFhs6'%%r1nnG%%s1nnG%%r2nnG%%s2nnG%%delnGF$F$C)>F]o*$,
&F[`lFCF\`lFHFH>F<-F>6#-Ff\l6#*&FZFCF]oFC>FJ-F>6#-Ff\l6#,$*&FGFCF]oFCFH>FS-F>6#
-Ff\l6#,$*&FQFCF]oFCFH>Ffn-F>6#-Ff\l6#*&FBFCF]oFC-Fip6(F\\lFBFGFerFQFZ-Fip6(%1o
bratnaya_zamenaGFerF<FJFSFfn6#Q9zamena,~obratnaya~dannoyF$F$F$%(l2systoGf*Fh_oF
fdpF$F$C/>F<F]`o>FJFb`o>FSFf`o>FfnF\ao>F]oFaao>FdoFeao>F[pFiao>FiyF_bo-Fip6&%%m
nojGFBFGFQ-Fip6'%#H2GFZFFFDFOF`hpF]_oF__o6#QApo~obsch.mnoj.~i~H2~daet~systemuF$
F$F$%$l1pGf*F^sFisF$F$C3>F<Fft>FJFfu>FSFcv>FfnF^w>F]oFjw>FdoFdx>F[pF\y>FiyFjyFg
[lFj[l-Fip6(F_\lF]ilF_ilFer-F>Fj\o-F>F`]oF`\lF[]lF^]lF`]lFh]lF[^lF^^lF$F$%"RGf*
F)F2F$F$C*>F<F=>FJFK>FSFT>FfnFgn>F]oF^o>FdoFeo>F[pF\p-Fip6%FdrFerF[p6#Q6schitae
t~R3~v~sistemeF$F$F$%&sols2Gf*62F_dmF`dmFadmFbdmFcdmFddmFedmFfdm%$i1nG%$i2nG%$i
3nG%$i4nG%$i5nG%$i6nG%$i7nG%$i8nG68Fj^lF[_lF\_lF]_lF^_lF__lF`_lFa_lF\emF]emF^em
F_emF`emFaemFbemFcemFgdmFhdmFidmFjdmFdem%"MGF$F$CD>Fjhn-F[gm6&FifmF\gnFfgnF`hn>
Fiz*&,&*&F`hnFC-Ff[m6(FBFGFQFZFifmFfgnFCFC*&F\gnFC-Ff[m6(FFFDFOFXFifmFfgnFCFHFC
FjhnFH>Fa[l*&,:**FBFCFifmFdpF\gnFCF`hnFCF`p*,FGFCFifmFCF\gnFCFfgnFCF`hnFCFdp*(F
GFCFifmFdpF`hnFdpFC**FQFCFifmFCFfgnFCF`hnFdpFdp**FQFCF\gnFCFfgnFdpF`hnFCFC*(FZF
CFfgnFdpF`hnFdpF`p*(FFFCFifmFdpF\gnFdpFahm**FDFCFifmFCF\gnFdpFfgnFCFbp**FDFCFif
mFdpF\gnFCF`hnFCFH*,FOFCFifmFCF\gnFCFfgnFCF`hnFCFbp*(FOFCF\gnFdpFfgnFdpFH**FXFC
F\gnFCFfgnFdpF`hnFCFahmFCFjhnFH>Fcbl*&,:**FBFCFifmFCF\gnFdpF`hnFCF`p**FGFCFifmF
CF\gnFCF`hnFdpFdp**FGFCF\gnFdpFfgnFCF`hnFCFC**FQFCF\gnFCFfgnFCF`hnFdpFdp*(FQFCF
ifmFCF`hnF`pFC*(FZFCFfgnFCF`hnF`pF`p*(FFFCFifmFCF\gnF`pFahm**FDFCFifmFCF\gnFdpF
`hnFCFbp*(FDFCF\gnF`pFfgnFCFH**FOFCF\gnFdpFfgnFCF`hnFCFbp**FOFCFifmFCF\gnFCF`hn
FdpFH**FXFCF\gnFCFfgnFCF`hnFdpFahmFCFjhnFH>Facl*&,&*&F`hnFC-Ff[m6(FBFGFQFZF\gnF
`hnFCFC*&F\gnFC-Ff[m6(FFFDFOFXF\gnF`hnFCFHFCFjhnFH>F]dl*&,&*&FfgnFCFj_qFCFH*&Fi
fmFCF]`qFCFCFCFjhnFH>Fjdl*&,:*(FFFCFifmF`pF\gnFCF`p**FDFCFifmFdpF\gnFCFfgnFCFdp
*(FDFCFifmF`pF`hnFCFC**FOFCFifmFdpFfgnFCF`hnFCFdp**FOFCFifmFCF\gnFCFfgnFdpFC**F
XFCFifmFCFfgnFdpF`hnFCF`p**FBFCFifmFdpF\gnFCFfgnFCFahm**FGFCFifmFCF\gnFCFfgnFdp
Fbp**FGFCFifmFdpFfgnFCF`hnFCFH**FQFCFifmFCFfgnFdpF`hnFCFbp*(FQFCF\gnFCFfgnF`pFH
*(FZFCFfgnF`pF`hnFCFahmFCFjhnFH>Feel*&,:Fh`qF`pFj`qFdpFi`qFCF[aqFdp*(FOFCFifmFd
pF`hnFdpFC**FXFCFifmFCFfgnFCF`hnFdpF`p**FBFCFifmFCF\gnFdpFfgnFCFahmFc`qFbp*(FGF
CF\gnFdpFfgnFdpFHFf`qFbpFe`qFHFg`qFahmFCFjhnFH>F^fl*&,&*&FfgnFCFabqFCFH*&FifmFC
FdbqFCFCFCFjhnFH>F<-F>Fh\n>FJ-F>Fc]n>FS-F>F^^n>Ffn-F>Fi^n>F]o-F>Fd_n>Fdo-F>F_`n
>F[p-F>Fj`n>Fiy-F>Fean>Fein-Ff]m6$FC"")>-FeinFe`m,&F<FCF^uFH>-FeinF`am,&FJFCF[u
FH>-FeinFbam,&FSFCF[blFH>-Fein6$FCF_in,&FfnFCFhalFH>-Fein6$FC""&,&F]oFC90FH>-Fe
in6$FC""',&FdoFC91FH>-Fein6$FC""(,&F[pFC92FH>-FeinFheq,&FiyFC93FHFhp-Fip6&F[jlF
\jlF]jlF^jl-Fip6&F_jlF`jlFajlFbjl-Fip6#%5poluchaemaya_sistemaG-FipF]gm-Fip6&F\g
qFbgqFhgqF\hq-Fip6#-%&solveG6#7*F[fqF^fqFafqFdfqFhfqF^gqFdgqFjgqFa_o6#Qcodelaet
~lineinuu~zamenu~v~sisteme~i~reshaet~sistemu~poluchennyh~uravneniyF$F$F$%'l2sys
tGf*Fh_oFfdpF$F$C.>F<F]`o>FJFb`o>FSFf`o>FfnF\ao>F]oFaao>FdoFeao>F[pFiao>FiyF_bo
F`\qFc\qF`hp-Fip6*F<FJFSFfnF]oFdoF[pFiyFf\qF$F$%)zamprocRGf*F^dmF[emF$F$CH>Fifm
Fjfm>FizF_gm>Fa[lFhgm>FcblFhhm>FaclFgim>F]dlF`jm>FjdlFejm>FeelFd[n>F^flF[\n>F<-
Ff\l6#Fgdq>FJ-Ff\l6#Fidq>FS-Ff\l6#F[eq>Ffn-Ff\l6#F]eq>F]o-Ff\l6#F_eq>Fdo-Ff\l6#
Faeq>F[p-Ff\l6#Fceq>Fiy-Ff\l6#Feeq@%FifnC$>F\gnFf`m>F^gnFf`mC$>F\gnFC>F^gnFC@%F
cgnC$>FfgnFf`m>FhgnFf`mC$>FfgnFdp>FhgnFC@%F]hnC$>F`hnFf`m>FbhnFf`mC$>F`hnF`p>Fb
hnFC@%FghnC$>FjhnFf`m>F\inFf`mC$>FjhnF_in>F\inFC@%FbinC$>FeinFf`m>FginFf`mC$>Fe
inF_in>FginFC@%F\jnC$>F_jnFf`m>FajnFf`mC$>F_jnF`p>FajnFC@%FfjnC$>FijnFf`m>F[[oF
f`mC$>FijnFdp>F[[oFC@%F`[oC$>Fc[oFf`m>Fe[oFf`mC$>Fc[oFC>Fe[oFC>Fj[oF[\o>F]\oF^
\oFhp-Fip6&-Ff\l6#-F>6#-Ff\l6#-Fg\n6$FB%)expandedG-Ff\l6#-F>6#-Ff\l6#-Fg\n6$FGF
d`r-Ff\l6#-F>6#-Ff\l6#-Fg\n6$FQFd`r-Ff\l6#-F>6#-Ff\l6#-Fg\n6$FZFd`r-Fip6&-Ff\l6
#-F>6#-Ff\l6#-Fg\n6$FFFd`r-Ff\l6#-F>6#-Ff\l6#-Fg\n6$FDFd`r-Ff\l6#-F>6#-Ff\l6#-F
g\n6$FOFd`r-Ff\l6#-F>6#-Ff\l6#-Fg\n6$FXFd`r-Fg]q6*FBFGFQFZFFFDFOFX-Fip6(F_\l-Ff
\l6#-F>6#-Fg\n6$Fi\oFd`r-Ff\l6#-F>6#-Fg\n6$F_]oFd`rFer-Ff\l6#-F>6#-Fg\n6$Fe]oFd
`r-Ff\l6#-F>6#-Fg\n6$F[^oFd`r-Fip6%Fb\lFer-F>6#-Fg\n6$Fc^oFd`rFf^oFj^o-Fip6&-Ff
\l6#-F>6#-Ff\l6#-Fg\n6$F<Fd`r-Ff\l6#-F>6#-Ff\l6#-Fg\n6$FJFd`r-Ff\l6#-F>6#-Ff\l6
#-Fg\n6$FSFd`r-Ff\l6#-F>6#-Ff\l6#-Fg\n6$FfnFd`r-Fip6&-Ff\l6#-F>6#-Ff\l6#-Fg\n6$
F]oFd`r-Ff\l6#-F>6#-Ff\l6#-Fg\n6$FdoFd`r-Ff\l6#-F>6#-Ff\l6#-Fg\n6$F[pFd`r-Ff\l6
#-F>6#-Ff\l6#-Fg\n6$FiyFd`rFa_oFd_oF$F$Fbbmf*6*F_sF`sFbsFcsFesFfsFgsFhs6&FjsF[t
F]tF^tF$F$C)>F<-F>6#-Ff\l6#*&,&*&FFFC,&FWFCF[oFHFCFC*&FOFCF`oFCFCFC,&*&FFFCFXFC
FC*&FOFCFDFCFHFH>FJ-F>6#-Ff\l6#*&,&*&FDFCFa[sFCFC*&FXFCF`oFCFCFCFc[sFH>FS-F>6#-
Ff\l6#,$*&,&*&FFFCFMFCFC*&FOFC,&FjnFCFYFHFCFCFCFc[sFHFH>Ffn-F>6#-Ff\l6#,$*&,&*&
FDFCFMFCFC*&FXFCFi\sFCFCFCFc[sFHFHF^[q-Fip6(F_\lFFFDFerFOFX-Fip6(F]]lF<FJQ!F$FS
Ffn6#Q7p,q~pri~zamene~pri~l=2F$F$F$%)jordle02Gf*Fh_oFj_oF$F$C2>F]dlF]`o>FjdlFb`
o>FeelFf`o>F^flF\ao>FifmFaao>F\gnFeao>FfgnFiao>F`hnF_bo>F<Fdbo>FJF[co>FfnFb\m>F
]oFg\m>FdoFj\m@%F^]mC$>F[pFe]m>FiyFa^mC&>FaclF_]m>F[pFa_m>FiyFi_m@$Fc`mC$>F[pFi
`m>FiyF[amF\amFabm6#Qboprivodit~sistemu~k~jord~forme~v~sluchae~l=2,~D<0,zadanno
y~alp,bet,gam,HF$F$F$%$pm1Gf*Fjil64FdjlFejlFbtFct%&rez2nGF3F4F5F6F7F8F9FfjlFgjl
FhjlFijl%#gpGF^[mF$F$C:>F<Fa[m>FJF[\m>F]dlFb\m>FjdlFg\m>Feel-Ff\l6#*&F<FCF]dlFH
@%/-F`]m6$FeelFh[mFCC$>F^fl-Ff]m6#7#7$Fi`s-F`]m6$FeelFi[m>Fifm-Ff]m6#7$7%-F>6#-
Ff\l6#-F`]m6$F]dlFb]m-F>6#-Ff\l6#*&-F`]m6$F]dlFh[mFCFi[mFH-F>6#-Ff\l6#-F`]m6$F]
dlF_^m7%-F>6#-Ff\l6#-F`]m6$FjdlFb]m-F>6#-Ff\l6#*&-F`]m6$FjdlFh[mFCFi[mFH-F>6#-F
f\l6#-F`]m6$FjdlF_^mC&>F\gnFi`s>F^fl-Ff]m6#7#7$*&Fi`sFCF\gnFH*&FaasFCF\gnFH>Fif
m-Ff]m6#7$7%-F>6#*&FjasFCF\gnFC-F>6#*&F`bsFCF\gnFC-F>6#-Ff\l6#*&FibsFCF\gnFC7%-
F>6#*&F^csFCF\gnFC-F>6#*&FdcsFCF\gnFC-F>6#-Ff\l6#*&F]dsFCF\gnFC@$2&F^flFe`mFf`m
C$>F^fl,$F^flFH>Fifm,$FifmFH>FS-F>6#-Ff\l6#,&*$&FifmF`amFdpFC*&&FifmFe`mFC&Fifm
FbamFCF_[l>Ffn-F>6#-Ff\l6#,&*$&FifmF[bmFdpFC*&&FifmF^bmFC&Fifm6$FdpF`pFCF_[l>F]
o-F>6#-Ff\l6#-%(combineG6#,&*$,&*&FegsFCFahsFCFC*&FfgsFCF`hsFCFHFdpFC*&,&*&Fegs
FCF^hsFCFC*&FcgsFCF`hsFCFHFC,&*&FcgsFCFahsFCFC*&FfgsFCF^hsFCFHFCFH>FdoF=>F[pFK>
FiyFT>FizFgn>Fa[lF^o>FcblFeo>Facl-F>6#,.*$FiyF`pFC*(FdoFCFiyFCFcblFCFbp*&F[pFdp
FcblFCFC*&FdoFCFa[lFdpFC*(FdoFCFizFCFcblFCFH*(F[pFCFiyFCFa[lFCFHF\qF^qFd`pFf`p-
Fip6*F^flFifmQ'~~~~~~F$%&discrG-Ff]m6#7$7#FS7#FfnQ&~~~~~F$Fj]lF]o-Fip6*FbqFdoQ$
~~~F$FeqF[pFc[tFhqFiy-Fip6*F[rFizFc[tF^rFa[lFc[tFarFcbl-Fip6+Fi[lFaclFfrFajsFcj
sFdjs,$FbjsFbp,$FejsFH,$FfjsFH6#Q`qraskladyvaet~mnogochleny~v~sisteme,zadannoy~
matricey~A,~schitaet~delty,~rez,obw.mnoj.,G,diskriminantyF$F$F$Fi\lf*6&Fh[m%#y1
GFi[m%#y2GF$F[dpF$FcipF$F$F$%+zamprocl2oGf*FedpFfdpF$F$C+>F<F]`o>FJFb`o>FSFf`o>
FfnF\ao>F]oFaao>FdoFeao>F[pFiao>FiyF_bo-F\dmFaepFbepF$F$%,zamprocl1_RGf*Fb^lFi^
lF$F$C7>F<Fd_l>FJFh_l>FSF^`l>FfnFb`l>F]oFe`l>FdoFh`l>F[pF\al>FiyF`al>Fa[lFcal>F
cblFdbl>FaclFbcl>F]dlF^dl>FjdlF[el>FeelFfel>F^flF_fl>FizF^glFjglF]hlFchlFail-Fi
p6%%'R2_newGFerF^flFfilF$F$%+zamprocratGf*F^dmF[emF$F$CO>FifmFjfm>FizF_gm>Fa[lF
hgm>FcblFhhm>FaclFgim>F]dlF`jm>FjdlFejm>FeelFd[n>F^flF[\n>F<Fijq>FJF\[r>FSF_[r>
FfnFb[r>F]oFe[r>FdoFh[r>F[pF[\r>FiyF^\r>F<-Ff\l6#-F>F`bn>FJ-Ff\l6#-F>Fjbn>FS-Ff
\l6#-F>Fdcn>Ffn-Ff\l6#-F>F^dn>F]o-Ff\l6#-F>Fhdn>Fdo-Ff\l6#-F>Fben>F[p-Ff\l6#-F>
F\fn>Fiy-Ff\l6#-F>Fffn@%FifnC$>F\gnFf`m>F^gnFf`mC$>F\gnFC>F^gnFC@%FcgnC$>FfgnFf
`m>FhgnFf`mC$>FfgnFdp>FhgnFC@%F]hnC$>F`hnFf`m>FbhnFf`mC$>F`hnF`p>FbhnFC@%FghnC$
>FjhnFf`m>F\inFf`mC$>FjhnF_in>F\inFC@%FbinC$>FeinFf`m>FginFf`mC$>FeinF_in>FginF
C@%F\jnC$>F_jnFf`m>FajnFf`mC$>F_jnF`p>FajnFC@%FfjnC$>FijnFf`m>F[[oFf`mC$>FijnFd
p>F[[oFC@%F`[oC$>Fc[oFf`m>Fe[oFf`mC$>Fc[oFC>Fe[oFC>Fj[oF[\o>F]\oF^\oFhpF\qF^q-F
ip6(F_\l-Ff\l6#-%'expandG6#-%,rationalizeGFj\o-Ff\l6#-Ffet6#-FietF`]oFer-Ff\l6#
-Ffet6#-FietFf]o-Ff\l6#-Ffet6#-FietF\^o-Fip6%Fb\lFer-Ff\l6#-F>6#-Ff\l6#-Ffet6#-
FietF`^oFf^oFj^o-Fip6&-Fg\n6$-Ffet6#-FietFe`pFd`r-Fg\n6$-Ffet6#-FietFg`pFd`r-Fg
\n6$-Ffet6#-Fiet6#FSFd`r-Fg\n6$-Ffet6#-Fiet6#FfnFd`r-Fip6&-Fg\n6$-Ffet6#-Fiet6#
F]oFd`r-Fg\n6$-Ffet6#-Fiet6#FdoFd`r-Fg\n6$-Ffet6#-Fiet6#F[pFd`r-Fg\n6$-Ffet6#-F
iet6#FiyFd`rFa_oFd_oF$F$F]amf*6)Fc^lFd^lFi_oFesFfsFgsFhsF^bpF$F$C(>F<-Fihs6#-F>
6#-Ff\l6#,(*&FBFCFZFdpFC*(FGFCFZFCFDFCFC*&FQFCFDFdpFC>FJ-Fihs6#-F>6#-Ff\l6#,(*(
FBFCFZFCFFFCFdp*&FGFC,&FioFCFcglFCFCFC*(FQFCFDFCFOFCFdp>FS-Fihs6#-F>6#-Ff\l6#,(
*&FBFCFFFdpFC*(FGFCFFFCFOFCFC*&FQFCFOFdpFC-Fip6&F\\lFBFGFQ-Fip6(F_\lFZFFFerFDFO
-Fip6&F]]lF<FJFS6#QFalpha,~beta,~gamma~pri~zamene~pri~l=2F$F$F$%%solsGf*Fg^qF`_
qF$F$CD>FjhnFd_q>FizFg_q>Fa[lF``q>FcblF_aq>FaclF^bq>F]dlFgbq>FjdlF\cq>FeelF[dq>
F^flFbdq>F<Fgdq>FJFidq>FSF[eq>FfnF]eq>F]oF_eq>FdoFaeq>F[pFceq>FiyFeeq>FeinFgeq@
%/F^uFf`m>F[fqF<>F[fqFf`m@%/F[uFf`m>F^fqFJ>F^fqFf`m@%/F[blFf`m>FafqFS>FafqFf`m@
%/FhalFf`m>FdfqFfn>FdfqFf`m@%/F\gqFf`m>FhfqF]o>FhfqFf`m@%/FbgqFf`m>F^gqFdo>F^gq
Ff`m@%/FhgqFf`m>FdgqF[p>FdgqFf`m@%/F\hqFf`m>FjgqFiy>FjgqFf`mFhpF\qF^qFahqFdhqFe
hqFghqFa_oF]iqF$F$F\dmf+6.F[jlF\jlF]jlF^jlF_jlF`jlFajlFbjlFgdmFhdmFidmFjdm64Fj^
lF[_lF\_lF]_lF^_lF__lF`_lFa_lF\emF]emF^emF_emF`emFaemFbemFcemFdemFa_qF$F$CQ>Fif
mFjfm>FizF_gm>Fa[lFhgm>FcblFhhm>FaclFgim>F]dlF`jm>FjdlFejm>FeelFd[n>F^flF[\n>F<
F`\n>FJF\]n>FSFg]n>FfnFb^n>F]oF]_n>FdoFh_n>F[pFc`n>FiyF^an>FizFian>Fa[lFcbn>Fcb
lF]cn>FaclFgcn>F]dlFadn>FjdlF[en>FeelFeen>F^flF_fn>F\gn-Ff]m6$FdpF_in>-F\gnFe`m
F<>-F\gnF`amFJ>-F\gnFbamFS>-F\gnFefqFfn>-F\gnF^bmF]o>-F\gnF[bmFdo>-F\gnFbhsF[p>
-F\gnFgbuFiy-Fip6,%2isxodnaya_sistemaGFizFa[lFcblFaclFerF]dlFjdlFeelF^flFc\o-Fi
p6%Fb\lFerFa^oFj^o-Fip6%F_dmFerF<-Fip6%F`dmFerFJ-Fip6%FadmFerFS-Fip6%FbdmFerFfn
-Fip6%FcdmFerF]o-Fip6%FddmFerFdo-Fip6%FedmFerF[p-Fip6%FfdmFerFiyOF\gnFd_oF$F$Ff
]m%%solnGf*6+F[jlF\jlF]jlF^jlF_jlF`jlFajlFbjl%$numGF$F$F$Cgn@$/F^u"#@C$-Fip6%%#
CFGFdpFC-Fc]u62FBFGFQFZFFFDFOFX%"kGFf`mFf`mFf`mFf`mFf`mFf`mFC@$/F^u"#BC$-Fip6%F
ieuFdpF`p-Fc]u62FBFGFQFZFFFDFOFX%"uGFf`mFf`mFf`mFf`mFCFf`mFf`m@$/F^u"#CC$-Fip6%
FieuFdpF_in-Fc]u62FBFGFQFZFFFDFOFXFf`mFefuFf`mFf`mFf`mFf`mFCFf`m@$/F^u"#DC$-Fip
6%FieuFdpFjfq-Fc]u62FBFGFQFZFFFDFOFXFCFf`mFf`mFf`mFCFf`mFf`mFf`m@$/F^u"#EC$-Fip
6%FieuFdpF`gq-Fc]u62FBFGFQFZFFFDFOFXFf`mFCFf`mFf`mFf`mFCFf`mFf`m@$/F^u"#FC$-Fip
6%FieuFdpFfgq-Fc]u62FBFGFQFZFFFDFOFXFf`mFCFf`mFf`mFCFf`mFf`mFf`m@$/F^u"#GC$-Fip
6%FieuFdpFieq-Fc]u62FBFGFQFZFFFDFOFXFf`mFf`mFCFf`mFf`mFCFf`mFf`m@$/F^u"$5#C$-Fi
p6%FieuFdp"#5-Fc]u62FBFGFQFZFFFDFOFXFf`mFf`mFf`mF\fuFCFf`mFf`mFf`m@$/F^u"#JC$-F
ip6%FieuF`pFC-Fc]u62FBFGFQFZFFFDFOFXFefuFCFf`mFf`mFf`mFf`mFf`mFC@$/F^u"#KC$-Fip
6%FieuF`pFdp-Fc]u62FBFGFQFZFFFDFOFXF\fuFf`mFefuFf`mFf`mFf`mFf`mFC@$/F^u"#MC$-Fi
p6%FieuF`pF_in-Fc]u62FBFGFQFZFFFDFOFXFefuFf`mFf`mFCFf`mFf`mFf`mFC@$/F^u"#PC$-Fi
p6%FieuF`pFfgq-Fc]u62FBFGFQFZFFFDFOFXFefuFCFf`mFf`mFf`mFCFf`mFf`m@$/F^u"#RC$-Fi
p6%FieuF`p""*-Fc]u62FBFGFQFZFFFDFOFXFCFf`mFf`mFefuFf`mFf`mFCFf`m@$/F^u"$5$C$-Fi
p6%FieuF`pFdiu-Fc]u62FBFGFQFZFFFDFOFXFf`mFefuFCFf`mFf`mFf`mFCFf`m@$/F^u"$7$C$-F
ip6%FieuF`p"#7-Fc]u62FBFGFQFZFFFDFOFXFCFefuFf`mFf`mFCFf`mFf`mFf`m@$/F^u"$8$C$-F
ip6%FieuF`p"#8-Fc]u62FBFGFQFZFFFDFOFXFf`mFf`mFCFCFf`mFf`mFf`mFC@$/F^u"$:$C$-Fip
6%FieuF`p"#:-Fc]u62FBFGFQFZFFFDFOFXFefuFf`mFf`mFCFf`mFCFf`mFf`m@$/F^u"$;$C$-Fip
6%FieuF`p"#;-Fc]u62FBFGFQFZFFFDFOFXFf`mFCFefuFf`mFf`mFCFf`mFf`m@$/F^u"$?$C$-Fip
6%FieuF`p"#?-Fc]u62FBFGFQFZFFFDFOFXFCFf`mFf`mFefuFCFf`mFf`mFf`m@$/F^u"$B$C$-Fip
6%FieuF`pF_fu-Fc]u62FBFGFQFZFFFDFOFXFf`mFefuFf`mF\fuFCFf`mFf`mFf`m@$/F^u"$C$C$-
Fip6%FieuF`pFhfu-Fc]u62FBFGFQFZFFFDFOFXFf`mFf`mFCFefuFCFf`mFf`mFf`m@$/F^u"#TC$-
Fip6%FieuF_inFC-Fc]u62FBFGFQFZFFFDFOFXFefu%"vGFf`mFf`mFf`mFf`mFCFC@$/F^u"#UC$-F
ip6%FieuF_inFdp-Fc]u62FBFGFQFZFFFDFOFXFefuFCF]avFf`mFf`mFf`mFf`mFC@$/F^u"#VC$-F
ip6%FieuF_inF`p-Fc]u62FBFGFQFZFFFDFOFXFefuFf`mF]avFf`mFf`mFf`mFCFC@$/F^u"#WC$-F
ip6%FieuF_inF_in-Fc]u62FBFGFQFZFFFDFOFXFefuF]avFf`mFCFf`mFf`mFf`mFC@$/F^u"#YC$-
Fip6%FieuF_inF`gq-Fc]u62FBFGFQFZFFFDFOFXFefuFf`mFf`mF]avFf`mFf`mFCFC@$/F^u"#[C$
-Fip6%FieuF_inFieq-Fc]u62FBFGFQFZFFFDFOFXFefuFf`mF]avFf`mFf`mFCFf`mF\fu@$/F^u"#
\C$-Fip6%FieuF_inF]\v-Fc]u62FBFGFQFZFFFDFOFXFefuFf`mF]avFCFf`mFf`mFf`mFC@$/F^u"
$5%C$-Fip6%FieuF_inFdiu-Fc]u62FBFGFQFZFFFDFOFXFCFefuFf`mF]avFf`mFf`mFCFf`m@$/F^
u"$8%C$-Fip6%FieuF_inFg]v-Fc]u62FBFGFQFZFFFDFOFXFefuFf`mFf`mFCFf`mFCFf`mF]av@$/
F^u"$9%C$-Fip6%FieuF_in"#9-Fc]u62FBFGFQFZFFFDFOFXFf`mFefuFefuFf`mFf`mFCFf`mFH@$
/F^u"$;%C$-Fip6%FieuF_inFi^v-Fc]u62FBFGFQFZFFFDFOFXFefuFf`mFCF]avFf`mFf`mFCFf`m
@$/F^u"$<%C$-Fip6%FieuF_in"#<-Fc]u62FBFGFQFZFFFDFOFXFefuF]avFf`mFCFf`mFCFf`mFf`
m@$/F^u"$=%C$-Fip6%FieuF_in"#=-Fc]u62FBFGFQFZFFFDFOFXFf`mFf`mFCFHFf`mFf`mFCFH@$
/F^u"$?%C$-Fip6%FieuF_inFb_v-Fc]u62FBFGFQFZFFFDFOFXFf`mFCFf`mFefuFf`mFCFf`mFefu
@$/F^u"$@%C$-Fip6%FieuF_inFeeu-Fc]u62FBFGFQFZFFFDFOFXFefuFf`mFf`mF]avFCFf`mFf`m
FC@$/F^u"$A%C$-Fip6%FieuF_in"#A-Fc]u62FBFGFQFZFFFDFOFXFefuFf`mFf`mF]avFf`mFCFCF
f`m@$/F^u"$B%C$-Fip6%FieuF_inF_fu-Fc]u62FBFGFQFZFFFDFOFXFf`mFefuF]avFf`mFf`mFCF
CFf`m@$/F^u"$D%C$-Fip6%FieuF_inF`gu-Fc]u62FBFGFQFZFFFDFOFXFefuFf`mF]avFCFf`mFCF
f`mFf`m@$/F^u"$E%C$-Fip6%FieuF_inFhgu-Fc]u62FBFGFQFZFFFDFOFXFCFefuFf`mF]avFCFf`
mFf`mFf`m@$/F^u"$G%C$-Fip6%FieuF_inFhhu-Fc]u62FBFGFQFZFFFDFOFXFf`mFefuFf`mF]avF
CFf`mFf`mFC@$/F^u"$J%C$-Fip6%FieuF_inFiiu-Fc]u62FBFGFQFZFFFDFOFXFefuFf`mFCF]avF
CFf`mFf`mFf`m@$/F^u"$K%C$-Fip6%FieuF_inFaju-Fc]u62FBFGFQFZFFFDFOFXFf`mFf`mFefuF
]avFCFf`mFf`mFC@$/F^u"$M%C$-Fip6%FieuF_inFiju-Fc]u62FBFGFQFZFFFDFOFXFf`mFefuFf`
mF]avFCFf`mF\fuFf`m@$/F^u"$N%C$-Fip6%FieuF_in"#N-Fc]u62FBFGFQFZFFFDFOFXFf`mFefu
FCF]avFCFf`mFf`mFf`m@$/F^u"$O%C$-Fip6%FieuF_in"#O-Fc]u62FBFGFQFZFFFDFOFXFf`mFf`
mFCFefuFCFf`mF]avFf`m@$/F^u"$P%C$-Fip6%FieuF_inFa[v-Fc]u62FBFGFQFZFFFDFOFXFf`mF
f`mFefuF]avFCFCFf`mFf`m@$/F^u"#dC$-Fip6%FieuFjfqFfgq-Fc]u62FBFGFQFZFFFDFOFXFefu
,$FefuFHFefuFf`mFCFf`mFf`mFC@$/F^u"$A&C$-Fip6%FieuFjfqFghv-Fc]u62FBFGFQFZFFFDFO
FXFf`mFefuFd^wFefuFCFf`mFf`mFC@$/F^u"#hC$-Fip6%FieuF`gqFC-Fc]u62FBFGFQFZFFFDFOF
XFefuFefu*&FefuFCF]avFCFf`mFf`mFCFCF]av@$/F^u"#jC$-Fip6%FieuF`gqF`p-Fc]u62FBFGF
QFZFFFDFOFXFC,&FCFCF]avFHFf`m,$*$F]avFdpFHFf`mFCFCF]av@$/F^u"#kC$-Fip6%FieuF`gq
F_in-Fc]u62FBFGFQFZFFFDFOFXFCF]avFCF]avFf`mFCFf`mFC@$/F^u"#mC$-Fip6%FieuF`gqF`g
q-Fc]u62FBFGFQFZFFFDFOFXFefu*&FefuFC,&*$F]avFbpFCF]avFHFCFf`m*&FefuFCF]avFahmFC
Ff`m,&*$F]avFHFCF``wFHFC@$/F^u"#nC$-Fip6%FieuF`gqFfgq-Fc]u62FBFGFQFZFFFDFOFXFef
uF]av,$F]avFH,&FefuFCF]avFCFCFf`mFf`mFC@$/F^u"#pC$-Fip6%FieuF`gqF]\v-Fc]u62FBFG
FQFZFFFDFOFXFf`mFCFbpFCFf`mFCFbpFC@$/F^u"$6'C$-Fip6%FieuF`gq"#6-Fc]u62FBFGFQFZF
FFDFOFXFefuF]avFefuF]avFCFf`mFCFf`m@$/F^u"$8'C$-Fip6%FieuF`gqFg]v-Fc]u62FBFGFQF
ZFFFDFOFXFefuFf`mFe_w*(FefuFCF]avFdp,&FCFCF]avFCFCFCFCFf`m*&F]avFCF[dwFdp@$/F^u
"#sC$-Fip6%FieuFfgqFdp-Fc]u62FBFGFQFZFFFDFOFXFefu%"wG,&*&FefuFCF]avFHFC*&F]avFC
,&Fe_wFCFedwFCFCFH,&FefuFC*&FedwFCF]avFHFCFCFf`mFeawFC@$/F^u"#")C$-Fip6%FieuFie
qFC-Fc]u62FBFGFQFZFFFDFOFXFCFahmF`pFHFCFahmF`pFH6#Qjrdelaet~lineinuu~zamenu~v~s
isteme~i~reshaet~sistemu~poluchennyh~uravneniy,~poluchaemaya~sistema~zadana~nom
erom~iz~spiska~dla~l=0F$F$F$F$
