M7R0
I&mylib=6"%&falseGE\[l/%*zamprocl1Gt,60%%alpnG%&betanG%$p1nG%$q1nG%$t1nG%$p2nG%
$q2nG%$t2nG%$r1pG%$s1pG%$r2pG%$s2pG>'%$lblG%(booleanGF%>'%$resGF9F%64%%a1nnG%%b
1nnG%%c1nnG%%d1nnG%%a2nnG%%b2nnG%%c2nnG%%d2nnG%'rezultG%%p1nnG%%q1nnG%%t1nnG%%p
2nnG%%q2nnG%%t2nnG%%res2G%"MG%"GGF$F$C4>8$-%'factorG6#*&9$"""9&FX>8%-FT6#,&*&FW
FX9'FXFX*&FYFX9%FXFX>8&-FT6#,&*&FWFX9(FXFX*&F\oFXFjnFXFX>8'-FT6#*&FcoFXF\oFX>8(
-FT6#*&FWFX9)FX>8)-FT6#,&*&FWFX9*FXFX*&F\oFXF_pFXFX>8*-FT6#,&*&FWFX9+FXFX*&F\oF
XFfpFXFX>8+-FT6#*&F\oFXF^qFX>8--FT6#*&,.*(9,""#9/FXFYFXFX*(F\rF]r9-FXF_pFX!""**
9.FXFjnFXF\rFXF^rFXFX**F\rFXFfpFXF`rFXFcrFXFar*(FcrF]rF^rFXFcoFXFX*(FcrF]rF`rFX
F^qFXFarFX,&*&F\rFXF^rFXFX*&F`rFXFcrFXFarFar>8.-FT6#*&,2**F\rFXF`rFXF^rFXFYFXF]
r*(F`rF]rF\rFXF_pFX!"#*(F^rF]rFjnFXF\rFXFX**F`rFXF^rFXFcrFXFjnFXFX**F`rFXF^rFXF
\rFXFfpFXFar*(F`rF]rFfpFXFcrFXFar*(F^rF]rFcrFXFcoFXF]r**FcrFXF^rFXF`rFXF^qFXFbs
FXFgrFar>8/-FT6#*&,.*(F`rF]rF^rFXFYFXFX*&F`r""$F_pFXFar*(F`rFXF^rF]rFjnFXFX*(F`
rF]rF^rFXFfpFXFar*&F^rFatFcoFXFX*(F^rF]rF`rFXF^qFXFarFXFgrFar>80-FT6#,$*&,.*(F
\rF]rFcrFXFYFXFX*&F\rFatF_pFXFar*(F\rFXFcrF]rFjnFXFX*(F\rF]rFcrFXFfpFXFar*&FcrF
atFcoFXFX*(FcrF]rF\rFXF^qFXFarFXFgrFarFar>81-FT6#,$*&,2**F\rFXF`rFXFcrFXFYFXF]r
F_rFbsFbrFX*(FcrF]rFjnFXF`rFXFX*(F\rF]rFfpFXF^rFXFarFdrFarFerF]r**FcrFXF^rFXF\r
FXF^qFXFbsFXFgrFarFar>82-FT6#,$*&,.*(F`rF]rFcrFXFYFXFXFasFarFdsFXFesFarFgsFX*(F
^rF]rF\rFXF^qFXFarFXFgrFarFar>83-FT6#,&*$,&*&FfqFXF_vFXFX*&FgtFXFjsFXFarF]rFX*&
,&*&FfqFXFduFXFX*&FgtFXF[sFXFarFX,&*&F[sFXF_vFXFX*&FduFXFjsFXFarFXFar@$91C&>85-
%'MatrixG6#7$7%-FT6#FY-FT6#Fjn-FT6#Fco7%-FT6#F_p-FT6#Ffp-FT6#F^q>8,-FT6#,&*$,&*
&FYFXF^qFXFX*&F_pFXFcoFXFarF]rFX*&,&*&FYFXFfpFXFX*&F_pFXFjnFXFarFX,&*&FjnFXF^qF
XFX*&FfpFXFcoFXFarFXFar-%(pprintfG6$Q'G~=~%aF$F[x-F_z6$Q4Resultant~of~G:~~%aF$F
_y>84-%(zamprocG60FRFenF^oFfoF[pFapFipFaqF\rF`rFcrF^r/._F$F<F%/._F$F890OFfzF$F$
F$6#"#7F]xF_zf*6#'%"SG%'stringG6)%"XG%"LG%"rG%"nG%"iG%"jG%"kGF$F$C(>Fen7#-_%,St
ringToolsG%)RegSplitG6$Q#%aF$FW>FR7#&9"6#;F]rFar>F^o%%NULLG>FapFX?(F[pFXFX-%%no
psG6#Fen%%trueGC&>Ffo-_Ff\l%:CountCharacterOccurrencesG6$&Fen6#F[pQ"%F$>F^o6$F^
o-_%,TypesettingG%#miG6#-%(sprintfG6$F^^l-%$seqG6$&FR6#Fip/Fip;Fap,(FapFXFfoFXF
arFX>Fap,&FapFXFfoFX@$1Fap-Fe]l6#FRC$>F^o6$F^o-%#opG6#-%$mapG6$_Fe^l%(TypesetG7
#&FR6#Fap>Fap,&FapFXFXFX-%&printG6#-_Fe^l%%mrowG6#F^oF$F$F$%$pm2Gf*6*%$a1pG%$b1
pG%$c1pG%$d1pG%$a2pG%$b2pG%$c2pG%$d2pG65%%P1nnG%%P2nnG%$dabG%$dacG%$dadG%$dbcG%
$dbdG%$dcdG%$RezG%%chisG%%znamG%$obwG%#omG%#hpG%'deltaHG%#mnG%#DpG%#DHG%#evGF$F
$C;>FR-FT6#-%)simplifyG6#-%"PG6(FWF\oFYFjn%#x1G%#x2G>Fen-FT6#-Fdcl6#-Fgcl6(FcoF
_pFfpF^qFiclFjcl>Ffq-%&numerG6#*&FRFXFenFar>F[s-%&denomGFedl>Fjs-Fdcl6#*&FRFXFf
qFar@%0-%&coeffG6$Fjs*$FiclF]r""!C%>FhvF`el>Fgt-F]x6#7#7%*&F`elFXFhvFar*(-Fael6
$FjsFiclFXFjclFarFhvFar*&-Fael6$Fjs*$FjclF]rFXFhvFar>Fdu-F]x6#7$7$*&-Fael6$FfqF
iclFXFhvFX*&-Fael6$FfqFjclFXFhvFX7$*&-Fael6$F[sFiclFXFhvFX*&-Fael6$F[sFjclFXFhv
FX@%0F^flFdelC%>Fhv*&F^flFXFjclFar>Fgt-F]x6#7#7%FdelF]flF`fl>FduFeflC%>FhvFafl>
Fgt-F]x6#7#7%FdelFdelF`fl>FduFefl>F_v-FT6#-Fdcl6#,&*&&Fdu6$FXFXFX&Fdu6$F]rF]rFX
FX*&&Fdu6$FXF]rFX&Fdu6$F]rFXFXFar>F[x-FT6#-Fdcl6#,&*$,&F`ilFXFbilFXF]rFXF_v!"%>
F^o-FT6#,&F^pFXFioFar>Ffo-FT6#,&FepFX*&FcoFXFYFXFar>F[p-FT6#,&F]qFX*&FcoFXFjnFX
Far>Fap-FT6#,&F_qFX*&F_pFXFYFXFar>Fip-FT6#,&FdqFXFjyFar>Faq-FT6#,&FeyFX*&FfpFXF
jnFXFar>F_y-FT6#,.*$F[pFatFX*(F^oFXF[pFXFaqFXFbs*&FfoF]rFaqFXFX*&F^oFXFipF]rFX*
(F^oFXFapFXFaqFXFar*(FfoFXF[pFXFipFXFar>Ffz-FT6#-Fdcl6#,&*$&FgtFfilF]rFX*&&FgtF
ailFX&Fgt6$FXFatFXFajl-F_z6#Q6Initial~coefficients:F$-Fj`l6&FWF\oFYFjn-Fj`l6&Fc
oF_pFfpF^q-F_z6#Q/Factorization:F$-F_z6%Q(%a~=~%aF$&Fgcl6#FXFR-F_z6%F`^m&Fgcl6#
F]rFen>86-_%.LinearAlgebraG%,EigenvaluesG6#Fdu-F_z6'Q1%a~=~%a;~%a~=~%aF$*$&%"pG
6#FdelF]rFgt&%"DGFd_mFfz-F_z6)QSH~=~%a,~~det~=~%a,~~%a~=~%a,~~eigenvalues:~~%a,
~%aF$FduF_vFf_mF[x&Fh^mFb^m&Fh^mFf^mF$F$F$%'l2systGt+6*F*F+%'gammanGF,F-F/F0>F7
F%6,F>F?F@FAFBFCFDFE%#p2G%#H2GF$F$C/>FR-FT6#-Fdcl6#Fin>Fen-FT6#-FdclF`o>F^o-FT6
#-Fdcl6#,&FioFX*&FYFXFjnFXFX>Ffo-FT6#-Fdcl6#Fjjl>F[p-FT6#-FdclF]p>Fap-FT6#-Fdcl
Fcp>Fip-FT6#-Fdcl6#,&F_qFXFd[mFX>Faq-FT6#-Fdcl6#Fiy>F_y-F]x6#7#7%FWF\oFY>Ffq-F]
x6#7$7$FjnFco7$F_pFfp-F_z6&QGInitial~coefficients:~~%a~=~%a;~H~=~%aF$Fa_mF_yFfq
-F_z6#Q.Matrix~(2x4):F$@%F^qC*-Fj`lFh_l-Fj`lFf]l-Fj`lF_al-Fj`l6#Ffo-Fj`lF_^l-Fj
`lFf`l-Fj`lF__l-Fj`l6#FaqC$-Fj`l6&FRFenF^oFfo-Fj`l6&F[pFapFipFaqF$F$F$6#""(%&de
ltaGf*6&Ficl%#y1GFjcl%#y2GF$6$%)operatorG%&arrowGF$,&FinFXF[oFarF$F$F$%"RGf*6*%
#a1G%#b1G%#c1G%#d1G%#a2G%#b2G%#c2G%#d2G6)F^blF_blF`blFablFbblFcblFdblF$F$C*>FRF
cjl>FenFgjl>F^oF\[m>FfoFa[m>F[pFf[m>FapFj[m>Fip-FT6#,.*$F^oFatFX*(FRFXF^oFXFapF
XFbs*&FenF]rFapFXFX*&FRFXF[pF]rFX*(FRFXFfoFXFapFXFar*(FenFXF^oFXF[pFXFar-F_z6$Q
0Resultant:~~~%aF$FipF$F$F$%%l1pGGf*6.F*F+F,F-F.F/F0F1%$r1nG%$s1nG%$r2nG%$s2nG6
,%&alpnnG%'betannGFGFHFIFJFKFL%#p1GFOF$F$C3>FR-FT6#,&*&FWFXF\rFXFX*&F\oFXFcrFXF
X>Fen-FT6#,&*&FWFXF`rFXFX*&F\oFXF^rFXFX>F^oFgq>FfoF\s>F[pF[t>FapFht>FipFeu>FaqF
`v>F_y-F]x6#7#7$FWF\o>FfqF\x-F_z6%Q?Initial~coefficients:~~%a~=~%aF$)Fb_m$FXFde
lF_y-F_z6$FazFfq-F_z6'Q>substitution:~~%a,~%a;~%a,~%aF$F\rF`rFcrF^r>F_y-F]x6#7#
7$FRFen>Ffq-F]x6#7$7%-FTF_al-FTFddm-FTF_^l7%-FTFf`l-FTF__l-FTFidm-F_z6%QJcoeffi
cients~after~substitution:~~%a~=~%aF$)Fb_mFbjmF_yFcjmF$F$F$Fhzt,61F]fmF^fmF_fmF
`fmFafmFbfmFcfmFdfm%#r1G%#s1G%#r2G%#s2G>F7F%>F;F%>'%&shortGF9Fg]l6FF>F?F@FAFBFC
FDFE%$a1nG%$b1nG%$c1nG%$d1nG%$a2nG%$b2nG%$c2nG%$d2nG%&DeltaG%#i1G%#i2G%#i3G%#i4
G%#i5G%#i6G%#i7G%#i8G%#ixG%#m1G%#m2G%#m3G%#m4G%#m5G%#m6G%#m7G%#m8G%#mxGFNF$F$CQ
>FfzFgr>F_y*&,&*&F^rFX-Fgcl6(FWF\oFYFjnF\rFcrFXFX*&F`rFX-Fgcl6(FcoF_pFfpF^qF\rF
crFXFarFXFfzFar>Ffq*&,:**FWFXF\rF]rF`rFXF^rFXFat*,F\oFXF\rFXF`rFXFcrFXF^rFXF]r*
(F\oFXF\rF]rF^rF]rFX**FYFXF\rFXFcrFXF^rF]rF]r**FYFXF`rFXFcrF]rF^rFXFX*(FjnFXFcr
F]rF^rF]rFat*(FcoFXF\rF]rF`rF]r!"$**F_pFXF\rFXF`rF]rFcrFXFbs**F_pFXF\rF]rF`rFXF
^rFXFar*,FfpFXF\rFXF`rFXFcrFXF^rFXFbs*(FfpFXF`rF]rFcrF]rFar**F^qFXF`rFXFcrF]rF^
rFXFi_nFXFfzFar>F[s*&,:**FWFXF\rFXF`rF]rF^rFXFat**F\oFXF\rFXF`rFXF^rF]rF]r**F\o
FXF`rF]rFcrFXF^rFXFX**FYFXF`rFXFcrFXF^rF]rF]r*(FYFXF\rFXF^rFatFX*(FjnFXFcrFXF^r
FatFat*(FcoFXF\rFXF`rFatFi_n**F_pFXF\rFXF`rF]rF^rFXFbs*(F_pFXF`rFatFcrFXFar**Ff
pFXF`rF]rFcrFXF^rFXFbs**FfpFXF\rFXF`rFXF^rF]rFar**F^qFXF`rFXFcrFXF^rF]rFi_nFXFf
zFar>Fjs*&,&*&F^rFX-Fgcl6(FWF\oFYFjnF`rF^rFXFX*&F`rFX-Fgcl6(FcoF_pFfpF^qF`rF^rF
XFarFXFfzFar>Fgt*&,&*&FcrFXFj^nFXFar*&F\rFXF]_nFXFXFXFfzFar>Fdu*&,:*(FcoFXF\rFa
tF`rFXFat**F_pFXF\rF]rF`rFXFcrFXF]r*(F_pFXF\rFatF^rFXFX**FfpFXF\rF]rFcrFXF^rFXF
]r**FfpFXF\rFXF`rFXFcrF]rFX**F^qFXF\rFXFcrF]rF^rFXFat**FWFXF\rF]rF`rFXFcrFXFi_n
**F\oFXF\rFXF`rFXFcrF]rFbs**F\oFXF\rF]rFcrFXF^rFXFar**FYFXF\rFXFcrF]rF^rFXFbs*(
FYFXF`rFXFcrFatFar*(FjnFXFcrFatF^rFXFi_nFXFfzFar>F_v*&,:Fh_nFatF[`nF]rFj_nFXF\`
nF]r*(FfpFXF\rF]rF^rF]rFX**F^qFXF\rFXFcrFXF^rF]rFat**FWFXF\rFXF`rF]rFcrFXFi_nFc
_nFbs*(F\oFXF`rF]rFcrF]rFarFf_nFbsFe_nFarFg_nFi_nFXFfzFar>Fhv*&,&*&FcrFXFbanFXF
ar*&F\rFXFeanFXFXFXFfzFar>FR-Fdcl6#-FT6#-Fdcl6#-%'normalG6#-Fdcl6#F_y>Fen-Fdcl6
#-FT6#-Fdcl6#-F_dn6#-Fdcl6#Ffq>F^o-Fdcl6#-FT6#-Fdcl6#-F_dn6#-Fdcl6#F[s>Ffo-Fdcl
6#-FT6#-Fdcl6#-F_dn6#-Fdcl6#Fjs>F[p-Fdcl6#-FT6#-Fdcl6#-F_dn6#-Fdcl6#Fgt>Fap-Fdc
l6#-FT6#-Fdcl6#-F_dn6#-FdclF]_m>Fip-Fdcl6#-FT6#-Fdcl6#-F_dn6#-Fdcl6#F_v>Faq-Fdc
l6#-FT6#-Fdcl6#-F_dn6#-Fdcl6#Fhv>F_y-Fdcl6#-FT6#-Fdcl6#-F_dn6#-Fdcl6#FW>Ffq-Fdc
l6#-FT6#-Fdcl6#-F_dn6#-Fdcl6#F\o>F[s-Fdcl6#-FT6#-Fdcl6#-F_dn6#-FdclFbx>Fjs-Fdcl
6#-FT6#-Fdcl6#-F_dn6#-FdclFdx>Fgt-Fdcl6#-FT6#-Fdcl6#-F_dn6#-FdclFfx>Fdu-Fdcl6#-
FT6#-Fdcl6#-F_dn6#-FdclFix>F_v-Fdcl6#-FT6#-Fdcl6#-F_dn6#-FdclF[y>Fhv-Fdcl6#-FT6
#-Fdcl6#-F_dn6#-FdclF]y@%/FRFdelC$>F[xFdel>8>FdelC$>F[xFX>Ff^oFX@%/FenFdelC$>Fh
^mFdel>8?FdelC$>Fh^mF]r>F__oFX@%/F^oFdelC$>87Fdel>8@FdelC$>Fg_oFat>Fi_oFX@%/Ffo
FdelC$>88Fdel>8AFdelC$>Fa`o""%>Fc`oFX@%/F[pFdelC$>89Fdel>8BFdelC$>F\aoFf`o>F^ao
FX@%/FapFdelC$>8:Fdel>8CFdelC$>FfaoFat>FhaoFX@%/FipFdelC$>8;Fdel>8DFdelC$>F`boF
]r>FbboFX@%/FaqFdelC$>8<Fdel>8EFdelC$>FjboFX>F\coFX>8=,2F[xFXFh^mFXFg_oFXFa`oFX
F\aoFXFfaoFXF`boFXFjboFX>8F,2Ff^oFXF__oFXFi_oFXFc`oFXF^aoFXFhaoFXFbboFXF\coFX>8
G-F]x6$F]rFf`o>-FgcoFailFR>-FgcoFfilFen>-FgcoFc]mF^o>-Fgco6$FXFf`oFfo>-FgcoFhil
F[p>-FgcoFcilFap>-Fgco6$F]rFatFip>-FgcoFicoFaq@$492C)-F_z6#Q0Initial~system:F$-
Fj`l6&F_yFfqF[sFjs-Fj`l6&FgtFduF_vFhv@$Fhw-Fjem6*FWF\oFYFjnFcoF_pFfpF^q-F_z6'Fg
jm-Fdcl6#-FT6#-Fdcl6#F\r-Fdcl6#-FT6#-Fdcl6#F`r-Fdcl6#-FT6#-Fdcl6#Fcr-Fdcl6#-FT6
#-Fdcl6#F^r-F_z6$Q+delta:~~%aF$-Fdcl6#-FT6#-Fdcl6#-Faem6&F\rF`rFcrF^r-F_z6#Q;sy
stem~after~substitution:F$@%F`[lC*F`dmFadmFbdmFcdmFedmFfdmFgdmFhdmC$F[emF]emOFg
coF$F$F$6#Fc[lF]x%%l2pHGt+60F*F+F_`mF,F-F/F0F]hmF^hmF_hmF`hm>'%$ifHGF9Fg]l>'%$i
fpGF9Fg]l>Ff\nFg]l6+FbhmFchm%(gammannGFGFHFJFKFb`mFc`mF$F$C.>FR-%(combineG6#-FT
6#-Fdcl6#,(*&FWFXF^qF]rFX*(F\oFXF^qFXF`rFXFX*&FYFXF`rF]rFX>Fen-Ffio6#-FT6#-Fdcl
6#,(*(FWFXF^qFXF\rFXF]r*&F\oFX,&*&F^qFXFcrFXFX*&F`rFXF\rFXFXFXFX*(FYFXF`rFXFcrF
XF]r>F^o-Ffio6#-FT6#-Fdcl6#,(*&FWFXF\rF]rFX*(F\oFXF\rFXFcrFXFX*&FYFXFcrF]rFX>Ff
o-FT6#-Fdcl6#*&,&*&F^qFX,&*&FjnFXFcrFXFX*&F_pFXF\rFXFarFXFX*&F`rFX,&*&FcoFXFcrF
XFX*&FfpFXF\rFXFarFXFXFX,&F[[pFXF\[pFarFar>F[p-FT6#-Fdcl6#*&,&*&F\rFXFa\pFXFX*&
FcrFXFe\pFXFXFXFh\pFar>Fap-FT6#-Fdcl6#,$*&,&*&F^qFX,&*&FjnFXF`rFXFX*&F_pFXF^qFX
FarFXFX*&F`rFX,&*&FcoFXF`rFXFX*&FfpFXF^qFXFarFXFXFXFh\pFarFar>Fip-FT6#-Fdcl6#,$
*&,&*&F\rFXF[^pFXFX*&FcrFXF_^pFXFXFXFh\pFarFar@$4FhwC'>FaqF^cm>F_yFccm-F_z6&Fjc
mFa_mFaqF_y-F_z6'FgjmF^qF\rF`rFcr-F_z6#QAcoefficients~after~substitution:F$>Faq
-F]x6#7#7%FRFenF^o>F_y-F]x6#7$7$FfoF[p7$FapFip@$F`[l-F_z6%F`^mFa_mFaq@$F^r-F_z6
$Q'H~=~%aF$F_yF$F$F$6#"#6%%solsGf*62F]fmF^fmF_fmF`fmFafmFbfmFcfmFdfmFb]nFc]nFd]
nFe]nFf]nFg]nFh]nFi]n68F>F?F@FAFBFCFDFEFi\nFj\nF[]nF\]nF]]nF^]nF_]nF`]nF_\nF`\n
Fa\nFb\nFa]nFNF$F$CD>Fa`o-&F"6#Faem6&FfzF[xFh^mFg_o>F_y*&,&*&Fg_oFX-Fgcl6(FWF\o
FYFjnFfzFh^mFXFX*&F[xFX-Fgcl6(FcoF_pFfpF^qFfzFh^mFXFarFXFa`oFar>Ffq*&,:**FWFXFf
zF]rF[xFXFg_oFXFat*,F\oFXFfzFXF[xFXFh^mFXFg_oFXF]r*(F\oFXFfzF]rFg_oF]rFX**FYFXF
fzFXFh^mFXFg_oF]rF]r**FYFXF[xFXFh^mF]rFg_oFXFX*(FjnFXFh^mF]rFg_oF]rFat*(FcoFXFf
zF]rF[xF]rFi_n**F_pFXFfzFXF[xF]rFh^mFXFbs**F_pFXFfzF]rF[xFXFg_oFXFar*,FfpFXFfzF
XF[xFXFh^mFXFg_oFXFbs*(FfpFXF[xF]rFh^mF]rFar**F^qFXF[xFXFh^mF]rFg_oFXFi_nFXFa`o
Far>F[s*&,:**FWFXFfzFXF[xF]rFg_oFXFat**F\oFXFfzFXF[xFXFg_oF]rF]r**F\oFXF[xF]rFh
^mFXFg_oFXFX**FYFXF[xFXFh^mFXFg_oF]rF]r*(FYFXFfzFXFg_oFatFX*(FjnFXFh^mFXFg_oFat
Fat*(FcoFXFfzFXF[xFatFi_n**F_pFXFfzFXF[xF]rFg_oFXFbs*(F_pFXF[xFatFh^mFXFar**Ffp
FXF[xF]rFh^mFXFg_oFXFbs**FfpFXFfzFXF[xFXFg_oF]rFar**F^qFXF[xFXFh^mFXFg_oF]rFi_n
FXFa`oFar>Fjs*&,&*&Fg_oFX-Fgcl6(FWF\oFYFjnF[xFg_oFXFX*&F[xFX-Fgcl6(FcoF_pFfpF^q
F[xFg_oFXFarFXFa`oFar>Fgt*&,&*&Fh^mFXFjapFXFar*&FfzFXF]bpFXFXFXFa`oFar>Fdu*&,:*
(FcoFXFfzFatF[xFXFat**F_pFXFfzF]rF[xFXFh^mFXF]r*(F_pFXFfzFatFg_oFXFX**FfpFXFfzF
]rFh^mFXFg_oFXF]r**FfpFXFfzFXF[xFXFh^mF]rFX**F^qFXFfzFXFh^mF]rFg_oFXFat**FWFXFf
zF]rF[xFXFh^mFXFi_n**F\oFXFfzFXF[xFXFh^mF]rFbs**F\oFXFfzF]rFh^mFXFg_oFXFar**FYF
XFfzFXFh^mF]rFg_oFXFbs*(FYFXF[xFXFh^mFatFar*(FjnFXFh^mFatFg_oFXFi_nFXFa`oFar>F_
v*&,:FhbpFatFjbpF]rFibpFXF[cpF]r*(FfpFXFfzF]rFg_oF]rFX**F^qFXFfzFXFh^mFXFg_oF]r
Fat**FWFXFfzFXF[xF]rFh^mFXFi_nFcbpFbs*(F\oFXF[xF]rFh^mF]rFarFfbpFbsFebpFarFgbpF
i_nFXFa`oFar>Fhv*&,&*&Fh^mFXFadpFXFar*&FfzFXFddpFXFXFXFa`oFar>FR-FTF`dn>Fen-FTF
[en>F^o-FTFfen>Ffo-FTFafn>F[p-FTF\gn>Fap-FTFggn>Fip-FTFahn>Faq-FTF\in>F\ao-F]x6
$FX"")@%/F\rFdel>-F\aoFailFR>F]hpFdel@%/F`rFdel>-F\aoFfilFen>FbhpFdel@%/FcrFdel
>-F\aoFc]mF^o>FghpFdel@%/F^rFdel>-F\aoFbdoFfo>F\ipFdel@%/F`[lFdel>-F\ao6$FX""&F
[p>FaipFdel@%/FhwFdel>-F\ao6$FX""'Fap>FhipFdel@%/F^eoFdel>-F\ao6$FXF`emFip>F_jp
Fdel@%/93Fdel>-F\aoFhgpFaq>FfjpFdelF`eoFg]mFi]m-F_z6#Q2Resulting~system:F$-Fj`l
F^ho-Fj`l6&F`[lFhwF^eoFdjp-Fj`l6#-%&solveG6#7*F]hpFbhpFghpF\ipFaipFhipF_jpFfjp-
F_z6#Q]r-----------------------------------------------------------------------
-------------------------------------------F$F$F$F$%'l1systGt+6,F*F+F,F-F.F/F0F
1>F7F%>F;F%66Fi\nFj\nF[]nF\]nF]]nF^]nF_]nF`]nFFFb]nFc]nFd]nFe]nFf]nFg]nFh]nFi]n
Fj]nFdhmFOF$F$C;>FRFV>FenFhn>F^oFao>FfoFio>F[pF^p>FapFdp>FipF\q>FaqFdq@%Fb^o>Ff
qFdel>FfqFX@%F[_o>F[sFdel>F[sF]r@%Fd_o>FjsFdel>FjsFat@%F^`o>FgtFdel>FgtFf`o@%Fi
`o>FduFdel>FduFf`o@%Fcao>F_vFdel>F_vFat@%F]bo>FhvFdel>FhvF]r@%Fgbo>FfzFdel>FfzF
X>F[x,2FfqFXF[sFXFjsFXFgtFXFduFXF_vFXFhvFXFfzFX>Fh^mFiim>Fg_oF\x-F_z6%F`jm)Fb_m
FbjmFh^m-F_z6$FazFg_o@$F`rC$>F_yF`yFbzF[dm@%F\rC*F`dmFadmFbdmFcdmFedmFfdmFgdmFh
dmC$F[emF]em-F_z6$Q*index:~%dF$F[xF$F$F$6#Figp%$pm1Gf*Fbal64F\blF]bl%$D1nG%$D2n
G%&rez2nGF^blF_blF`blFablFbblFcblFdblFeblFfblFgblFhbl%#gpGF[clF$F$C;>FRFacl>Fen
F\dl>FgtFcdl>FduFhdl>F_v-Fdcl6#*&FRFXFgtFar@%/-Fael6$F_vFiclFXC$>Fhv-F]x6#7#7$F
c`q-Fael6$F_vFjcl>Ffz-F]x6#7$7%-FT6#-Fdcl6#-Fael6$FgtFcel-FT6#-Fdcl6#*&-Fael6$F
gtFiclFXFjclFar-FT6#-Fdcl6#-Fael6$FgtFcfl7%-FT6#-Fdcl6#-Fael6$FduFcel-FT6#-Fdcl
6#*&-Fael6$FduFiclFXFjclFar-FT6#-Fdcl6#-Fael6$FduFcflC&>F[xFc`q>Fhv-F]x6#7#7$*&
Fc`qFXF[xFar*&F[aqFXF[xFar>Ffz-F]x6#7$7%-FT6#*&FdaqFXF[xFX-FT6#*&FjaqFXF[xFX-FT
6#-Fdcl6#*&FcbqFXF[xFX7%-FT6#*&FhbqFXF[xFX-FT6#*&F^cqFXF[xFX-FT6#-Fdcl6#*&FgcqF
XF[xFX@$2&FhvFailFdelC$>Fhv,$FhvFar>Ffz,$FfzFar>F^o-FT6#-Fdcl6#,&*$&FfzFfilF]rF
X*&&FfzFailFX&FfzFc]mFXFajl>Ffo-FT6#-Fdcl6#,&*$&FfzFcilF]rFX*&&FfzFhilFX&FfzFid
oFXFajl>F[p-FT6#-Fdcl6#-Ffio6#,&*$,&*&F_gqFXF[hqFXFX*&F`gqFXFjgqFXFarF]rFX*&,&*
&F_gqFXFhgqFXFX*&F]gqFXFjgqFXFarFX,&*&F]gqFXF[hqFXFX*&F`gqFXFhgqFXFarFXFar>FapF
cjl>FipFgjl>FaqF\[m>F_yFa[m>FfqFf[m>F[sFj[mFd]mFg]mFi]mF[^mF^^mFc^m-F_z6%F`^m)F
b_mFbjmFhv-F_z6$FazFfz-F_z6$Q3Discriminants:~~%aF$-F]x6#7$7#F^o7#Ffo-F_z6$FdzF[
pF$F$F$%*zamprocl2Gt,6.F*F+F_`mF,F-F/F0F_\nF`\nFa\nFb\n>F7F%6+F>F?F@FAFBFCFDFEF
NF$F$C,>FRFf`m>FenF[am>F^oF_am>FfoFfam>F[pF[bm>FapF_bm>FipFcbm>FaqFibm>F_y-Fhz6
0FRFenF^oFfoF[pFapFipFaqF^qF\rF`rFcrFjz/F^[lF^rOF_yF$F$F$6#F[apF]xFgclf*6(%"aG%
"bG%"cG%"dG%"xG%"yGF$FfemF$,**&FWFXFcoFatFX*(F\oFXFcoF]rF_pFXFX*(FYFXFcoFXF_pF]
rFX*&FjnFXF_pFatFXF$F$F$F$
